version: '3.8'

services:
  # MongoDB 数据库
  mongo:
    image: mongo:7.0
    container_name: destiny-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: destiny-analysis
    networks:
      - destiny-network

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: destiny-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/destiny-analysis
      - JWT_SECRET=destiny_analysis_jwt_secret_2024_change_in_production
      - JWT_EXPIRE=30d
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - destiny-network

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: destiny-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - destiny-network

networks:
  destiny-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

